Scheduler
sofia-kustikava/company-server pull request #7
Opened 2021-10-15 12:28 UTC by sofia-kustikava

2021-10-20 14:03 UTC, sofia-kustikava commented
**Added scheduler, mail sender, methods for changings subscriptions, methods for admin to block/unblock users and added custom exceptions.**

2021-10-21 07:00 UTC, AlRezz commented on src/main/java/com/example/companyserver/controller/AdminController.java
> +    public HttpStatus blockUser(@PathVariable Long userId) {
Надо возвращать ResponseEntity.ok() или ошибку

2021-10-21 07:39 UTC, AlRezz commented on src/main/java/com/example/companyserver/service/CompanyService.java
> +        log.info("Company was deleted with this id: " + symbol);
@Slf4j используй

2021-10-21 07:42 UTC, AlRezz commented on src/main/java/com/example/companyserver/service/InfoCompanyService.java
> +        QuoteEntity quote = quoteRepo.findByCompanies(companySymbol).orElseThrow(() -> new CompanyNotFoundException("Company not found"));
неправильная имплементация - здесь достаточно символа

2021-10-30 05:52 UTC, AlRezz requested changes
Надо читать замечания.

2021-10-31 19:51 UTC, sofia-kustikava commented
@AlRezz Я изменила все, что было в замечаниях. Что осталось еще сделать?

2021-11-01 06:10 UTC, AlRezz commented on src/test/java/com/example/companyserver/service/SubscriptionServiceTest.java
> +//        when(userRepo.findById(user.getId())).thenReturn(Optional.of(user));
что это такое?

2021-11-01 06:12 UTC, AlRezz requested changes
Вынести создание дополнительных объектов в отделный utility-класс. 
Сделать рефакторинг:
 - создавать объекты с помощью методов
 - удалить пустые линии

2021-11-01 09:45 UTC, sofia-kustikava commented on src/test/java/com/example/companyserver/service/SubscriptionServiceTest.java
> +//        when(userRepo.findById(user.getId())).thenReturn(Optional.of(user));
это тест метода, где пользователь выбирает подписку. Я его закомментила, потому что тест методов для подписок я не буду пока полностью делать.  SubscriptionService еще не готов полностью. Я могу убрать эти строки если нужно

2021-11-03 11:09 UTC, AlRezz approved these changes

2021-11-03 11:10 UTC, merged